/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Avatar_Idle.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          material={materials.M_Skin_MAT}
          geometry={nodes.Mesh015.geometry}
          skeleton={nodes.Mesh015.skeleton}
        />
        <skinnedMesh
          material={materials.Clothes_MAT}
          geometry={nodes.Mesh015_1.geometry}
          skeleton={nodes.Mesh015_1.skeleton}
        />
        <skinnedMesh
          material={materials.Clothes_MAT}
          geometry={nodes.Shoes_Sneaker.geometry}
          skeleton={nodes.Shoes_Sneaker.skeleton}
        />
        <skinnedMesh
          material={materials.M_Skin_MAT}
          geometry={nodes.Head_1.geometry}
          skeleton={nodes.Head_1.skeleton}
        />
        <skinnedMesh
          material={materials.Clothes_MAT}
          geometry={nodes.Head_Beard.geometry}
          skeleton={nodes.Head_Beard.skeleton}
        />
        <skinnedMesh
          material={materials.Clothes_MAT}
          geometry={nodes.Head_Hair_02.geometry}
          skeleton={nodes.Head_Hair_02.skeleton}
        />
        <skinnedMesh
          material={materials.M_Mask_Eyes_MAT}
          geometry={nodes.Mask_Eyes.geometry}
          skeleton={nodes.Mask_Eyes.skeleton}
        />
        <skinnedMesh
          material={materials.M_Mask_Mouth_MAT}
          geometry={nodes.Mask_Mouth.geometry}
          skeleton={nodes.Mask_Mouth.skeleton}
        />
        <skinnedMesh
          material={materials.Clothes_MAT}
          geometry={nodes.Mesh011.geometry}
          skeleton={nodes.Mesh011.skeleton}
        />
        <skinnedMesh
          material={materials.M_Skin_MAT}
          geometry={nodes.Mesh011_1.geometry}
          skeleton={nodes.Mesh011_1.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Avatar_Idle.glb')
