/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/BaseMale.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.Avatar_Hips} />
        <skinnedMesh
          material={materials.AvatarSkin_MAT}
          geometry={nodes.M_Feet_BaseMesh.geometry}
          skeleton={nodes.M_Feet_BaseMesh.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <skinnedMesh
          material={materials.AvatarSkin_MAT}
          geometry={nodes.M_Head_BaseMesh.geometry}
          skeleton={nodes.M_Head_BaseMesh.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}>
          <skinnedMesh
            material={materials.AvatarEyebrows_MAT}
            geometry={nodes.M_Mask_Eyebrows.geometry}
            skeleton={nodes.M_Mask_Eyebrows.skeleton}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.01, 0.01, 0.01]}
          />
          <skinnedMesh
            material={materials.AvatarEyes_MAT}
            geometry={nodes.M_Mask_Eyes.geometry}
            skeleton={nodes.M_Mask_Eyes.skeleton}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.01, 0.01, 0.01]}
          />
          <skinnedMesh
            material={materials.AvatarMouth_MAT}
            geometry={nodes.M_Mask_Mouth.geometry}
            skeleton={nodes.M_Mask_Mouth.skeleton}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.01, 0.01, 0.01]}
          />
        </skinnedMesh>
        <skinnedMesh
          material={materials.AvatarSkin_MAT}
          geometry={nodes.M_lBody_BaseMesh.geometry}
          skeleton={nodes.M_lBody_BaseMesh.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <skinnedMesh
          material={materials.AvatarSkin_MAT}
          geometry={nodes.M_uBody_BaseMesh.geometry}
          skeleton={nodes.M_uBody_BaseMesh.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/BaseMale.glb')
