/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/compressedv5.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['silver.001']} geometry={nodes['1-ears'].geometry} />
      <mesh material={materials['eyes.001']} geometry={nodes['1-eyes'].geometry} />
      <mesh material={materials['silver.001']} geometry={nodes['1-eyes001'].geometry} />
      <mesh material={materials['yellow-metal.001']} geometry={nodes['1-face'].geometry} />
      <mesh material={materials['black-grease.001']} geometry={nodes['1-neck'].geometry} />
      <mesh material={materials['silver.001']} geometry={nodes['1-bodybase'].geometry} />
      <mesh material={materials['yellow-metal.001']} geometry={nodes['1-bodybase001'].geometry} />
      <mesh material={materials['yellow-glow.001']} geometry={nodes['1-gem'].geometry} />
      <mesh material={materials['black-metal.001']} geometry={nodes['1-gem-holder'].geometry} />
      <mesh
        material={materials['black-metal.001']}
        geometry={nodes['1-leg-jointsL'].geometry}
        position={[-0.3, -1.54, 0]}
        rotation={[0, 0, 0.04]}
        scale={[1.16, 1.16, 1.16]}
      />
      <mesh
        material={materials['black-metal.001']}
        geometry={nodes['1-leg-jointsR'].geometry}
        position={[0.31, -1.53, 0]}
        rotation={[0, 0, -0.04]}
        scale={[1.13, 1.13, 1.13]}
      />
      <mesh material={materials['silver.001']} geometry={nodes['1-screws-body'].geometry} />
      <mesh material={materials['silver.001']} geometry={nodes['1-screws-body-bottom'].geometry} />
      <mesh material={materials['black-metal.001']} geometry={nodes['1-shoulderL'].geometry} />
      <mesh material={materials['black-metal.001']} geometry={nodes['1-shoulderR'].geometry} />
      <mesh material={materials['silver.001']} geometry={nodes['1-torso'].geometry} />
      <mesh material={materials['yellow-metal.001']} geometry={nodes['1-torso001'].geometry} />
      <mesh material={materials['black-grease.001']} geometry={nodes['1-waist'].geometry} />
      <mesh material={materials['black-grease.001']} geometry={nodes['1-armsL'].geometry} position={[0, 0.12, 0]} />
      <mesh material={materials['black-grease.001']} geometry={nodes['1-armsR'].geometry} position={[0, 0.12, 0]} />
      <mesh
        material={materials['yellow-metal.001']}
        geometry={nodes['1-hand-jointL'].geometry}
        position={[0, 0.12, 0]}
      />
      <mesh material={materials.silver} geometry={nodes['1-hand-jointR'].geometry} position={[1.87, -0.28, 0]} />
      <mesh material={materials['silver.001']} geometry={nodes['1-weaponL'].geometry} position={[0, 0.12, 0]} />
      <mesh
        material={materials['yellow-metal.001']}
        geometry={nodes['1-weaponL001'].geometry}
        position={[0, 0.12, 0]}
      />
      <mesh material={materials['black-metal.001']} geometry={nodes['1-weaponL002'].geometry} position={[0, 0.12, 0]} />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['1-weaponR'].geometry}
        position={[2.38, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        material={materials['yellow-metal.001']}
        geometry={nodes['1-weaponR001'].geometry}
        position={[2.38, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        material={materials['black-metal.001']}
        geometry={nodes['1-weaponR002'].geometry}
        position={[2.38, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[0, -3.39, 0]}>
        <mesh
          material={materials['silver.001']}
          geometry={nodes['1-Base'].geometry}
          position={[0, 3.39, 0]}
          scale={[1.5, 0.2, 1.5]}
        />
        <mesh
          material={materials['black-grease.001']}
          geometry={nodes['1-foot-jointsL'].geometry}
          position={[0, 3.39, 0]}
        />
        <mesh
          material={materials['black-grease.001']}
          geometry={nodes['1-foot-jointsR'].geometry}
          position={[0, 3.39, 0]}
        />
        <mesh material={materials['silver.001']} geometry={nodes['1-foot-screwsL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials['silver.001']} geometry={nodes['1-foot-screwsR'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials['silver.001']} geometry={nodes['1-footL'].geometry} position={[0, 3.39, 0]} />
        <mesh
          material={materials['yellow-metal.001']}
          geometry={nodes['1-footL001'].geometry}
          position={[0, 3.39, 0]}
        />
        <mesh material={materials['silver.001']} geometry={nodes['1-footR'].geometry} position={[0, 3.39, 0]} />
        <mesh
          material={materials['yellow-metal.001']}
          geometry={nodes['1-footR001'].geometry}
          position={[0, 3.39, 0]}
        />
        <mesh material={materials['black-grease.001']} geometry={nodes['1-LegsL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials['black-grease.001']} geometry={nodes['1-LegsR'].geometry} position={[0, 3.39, 0]} />
      </group>
      <mesh
        material={materials['face-mask']}
        geometry={nodes['2-eyes-screen'].geometry}
        position={[0, 0.05, 0.06]}
        scale={[0.55, 0.55, 0.55]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-face'].geometry}
        position={[0, 0.01, 0]}
        scale={[0.59, 0.59, 0.59]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-face001'].geometry}
        position={[0, 0.01, 0]}
        scale={[0.59, 0.59, 0.59]}
      />
      <mesh
        material={materials['emit-eye']}
        geometry={nodes['2-eyes'].geometry}
        position={[-0.16, 0.31, 0.5]}
        rotation={[-2.04, 0, Math.PI]}
        scale={[0.1, 0.03, 0.1]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-base-jointsL'].geometry}
        rotation={[0, 0, -0.4]}
        scale={[0.17, 0.09, 0.17]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-base-jointsR'].geometry}
        rotation={[0, 0, -0.4]}
        scale={[0.17, 0.09, 0.17]}
      />
      <mesh material={materials.green} geometry={nodes['2-Bodybase'].geometry} scale={[1.14, 1.25, 1.14]} />
      <mesh
        material={materials['gem-case']}
        geometry={nodes['2-gem'].geometry}
        rotation={[1.87, 0, 0]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        material={materials.gem}
        geometry={nodes['2-gem001'].geometry}
        rotation={[1.87, 0, 0]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-shouldersL'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-shouldersL001'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-shouldersR'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-shouldersR001'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-torso'].geometry}
        rotation={[0, 0, Math.PI]}
        scale={[0.65, 0.4, 0.65]}
      />
      <mesh material={materials['black-grease.001']} geometry={nodes['2-waist'].geometry} scale={[0.37, 0.22, 0.37]} />
      <mesh
        material={materials['black-grease.001']}
        geometry={nodes['2-ArmsL'].geometry}
        position={[-2.02, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.47, 0.09]}
      />
      <mesh
        material={materials['black-grease.001']}
        geometry={nodes['2-ArmsL001'].geometry}
        position={[-1.02, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.47, 0.09]}
      />
      <mesh
        material={materials['black-grease.001']}
        geometry={nodes['2-ArmsR'].geometry}
        position={[-0.69, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials['black-grease.001']}
        geometry={nodes['2-ArmsR001'].geometry}
        position={[-1.62, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-upper-armsL'].geometry}
        position={[-1.77, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.48, 0.26]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-upper-armsR'].geometry}
        position={[-1.42, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.48, 0.26]}
      />
      <mesh
        material={materials['emit-yellow']}
        geometry={nodes['2-WeaponL'].geometry}
        position={[-3.2, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-WeaponL001'].geometry}
        position={[-3.3, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-WeaponL002'].geometry}
        position={[-3.3, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.black}
        geometry={nodes['2-WeaponL003'].geometry}
        position={[-3.2, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials['emit-yellow']}
        geometry={nodes['2-WeaponR'].geometry}
        position={[-2.85, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-WeaponR001'].geometry}
        position={[-2.75, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-WeaponR002'].geometry}
        position={[-2.75, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.black}
        geometry={nodes['2-WeaponR003'].geometry}
        position={[-2.85, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh material={materials['silver.001']} geometry={nodes['2-Base'].geometry} scale={[1.5, 0.2, 1.5]} />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-FootL'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-FootL001'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-FootR'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials.green}
        geometry={nodes['2-FootR001'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-kneeL'].geometry}
        position={[-0.33, -1.98, 0]}
        rotation={[0, 0, -0.05]}
        scale={[0.13, 0.04, 0.13]}
      />
      <mesh
        material={materials['silver.001']}
        geometry={nodes['2-kneeR'].geometry}
        position={[-0.33, -1.98, 0]}
        rotation={[0, 0, -0.05]}
        scale={[0.13, 0.04, 0.13]}
      />
      <mesh
        material={materials['black-grease.001']}
        geometry={nodes['2-LegsL'].geometry}
        position={[-0.31, -1.84, 0]}
        rotation={[0, 0, -0.12]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials['black-grease.001']}
        geometry={nodes['2-LegsR'].geometry}
        position={[-0.31, -1.84, 0]}
        rotation={[0, 0, -0.12]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-Ears'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.11, 0.06, 0.11]}
      />
      <mesh
        material={materials['eye-emit']}
        geometry={nodes['3-Eye'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-Eye001'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-Eye002'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh
        material={materials.joints}
        geometry={nodes['3-Eye003'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh material={materials.white} geometry={nodes['3-Head-base'].geometry} scale={[0.39, 0.39, 0.31]} />
      <mesh material={materials.joints} geometry={nodes['3-Neck'].geometry} scale={[0.13, 0.1, 0.13]} />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-bodybase'].geometry}
        position={[0, 0, 0]}
        scale={[0.65, 0.46, 0.52]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-bodybase001'].geometry}
        position={[0, 0, 0]}
        scale={[0.65, 0.46, 0.52]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-gem'].geometry}
        position={[0, 0, 0]}
        rotation={[1.86, 0, 0]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        material={materials['gem.001']}
        geometry={nodes['3-gem001'].geometry}
        position={[0, 0, 0]}
        rotation={[1.86, 0, 0]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-shoulderL'].geometry}
        position={[-0.8, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-shoulderR'].geometry}
        position={[0.8, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-torso'].geometry}
        position={[0, 0.09, 0]}
        scale={[0.47, 0.47, 0.47]}
      />
      <mesh
        material={materials.joints}
        geometry={nodes['3-waist'].geometry}
        position={[0, 0.05, 0]}
        scale={[0.25, 0.12, 0.25]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-waist-leg-joint-L'].geometry}
        position={[0, 0.09, 0]}
        rotation={[0, 0, 0.68]}
        scale={[0.18, 0.09, 0.18]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-waist-leg-jointR'].geometry}
        position={[0, 0.09, 0]}
        rotation={[0, 0, 0.68]}
        scale={[0.18, 0.09, 0.18]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-elbowL'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.15, 0.15, 0.15]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-elbowR'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.15, 0.15, 0.15]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-HandL'].geometry}
        position={[0, -0.2, 0]}
        scale={[0.19, 0.05, 0.13]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-handR'].geometry}
        position={[0, -0.2, 0]}
        scale={[0.19, 0.05, 0.13]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-lowerArmL'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-lowerArmL001'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials['silver.003']}
        geometry={nodes['3-lowerArmR'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.white}
        geometry={nodes['3-lowerArmR001'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.joints}
        geometry={nodes['3-upper-armsL'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.35, 0.09]}
      />
      <mesh
        material={materials.joints}
        geometry={nodes['3-upper-armsR'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.35, 0.09]}
      />
      <group position={[0, -0.6, 0]}>
        <mesh
          material={materials['silver.001']}
          geometry={nodes['3-Base'].geometry}
          position={[0, 0.6, 0]}
          scale={[1.5, 0.2, 1.5]}
        />
        <mesh
          material={materials['silver.003']}
          geometry={nodes['3-footL'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.16, 0.16, 0.16]}
        />
        <mesh
          material={materials['silver.003']}
          geometry={nodes['3-FootR'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.16, 0.16, 0.16]}
        />
        <mesh
          material={materials.white}
          geometry={nodes['3-LowerLegL'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          material={materials.white}
          geometry={nodes['3-LowerLegR'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          material={materials.joints}
          geometry={nodes['3-thighsL'].geometry}
          position={[0, 0.64, 0]}
          rotation={[0, 0, -2.97]}
          scale={[0.1, 0.5, 0.1]}
        />
        <mesh
          material={materials.joints}
          geometry={nodes['3-thighsR'].geometry}
          position={[0, 0.64, 0]}
          rotation={[0, 0, -2.97]}
          scale={[0.1, 0.5, 0.1]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials['emit-blue']}
          geometry={nodes['4-eye'].geometry}
          position={[0, 0.63, 0.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-eye001'].geometry}
          position={[0, 0.63, 0.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-eye002'].geometry}
          position={[0, 0.63, 0.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-face'].geometry}
          position={[0, 0.41, 0]}
          scale={[0.4, 0.28, 0.4]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-Neck'].geometry}
          position={[0, 0.06, 0]}
          scale={[0.22, 0.12, 0.17]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials.red}
          geometry={nodes['4-Body-base'].geometry}
          position={[0, -0.99, 0]}
          scale={[0.99, 0.99, 0.69]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-body-connector'].geometry}
          position={[0, -1.54, 0]}
          scale={[0.36, 0.2, 0.28]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-gem'].geometry}
          position={[0, -0.39, 0.73]}
          rotation={[1.6, 0, 0]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          material={materials['emit-orange']}
          geometry={nodes['4-gem001'].geometry}
          position={[0, -0.39, 0.73]}
          rotation={[1.6, 0, 0]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-shoulderL'].geometry}
          position={[-0.9, -0.36, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.26, 0.18, 0.26]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-shoulderR'].geometry}
          position={[-0.9, -0.36, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.26, 0.18, 0.26]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-Torso'].geometry}
          position={[0, -1.63, 0]}
          scale={[0.58, 0.58, 0.58]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-armsL'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-armsL001'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-armsL002'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-armsR'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-armsR001'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-armsR002'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials['emit-orange']}
          geometry={nodes['4-handsL'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-handsL001'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-handsL002'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-handsL003'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['emit-orange']}
          geometry={nodes['4-handsR'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-handsR001'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-handsR002'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-handsR003'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh material={materials['silver.001']} geometry={nodes['4-Base'].geometry} scale={[2.01, 0.27, 2.01]} />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-footL'].geometry}
          position={[0.57, -4.52, 0.21]}
          scale={[0.26, 0.24, 0.45]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-footR'].geometry}
          position={[0.57, -4.52, 0.21]}
          scale={[0.26, 0.24, 0.45]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-LegsL'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-LegsL001'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-LegsL002'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials.red}
          geometry={nodes['4-LegsR'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials['black.001']}
          geometry={nodes['4-LegsR001'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials['silver.004']}
          geometry={nodes['4-LegsR002'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh
          material={materials['emit-eye']}
          geometry={nodes['5-eyes'].geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.12, 0.02, 0.12]}
        />
        <mesh
          material={materials['Material.003']}
          geometry={nodes['5-face'].geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.4, 0.36, 0.4]}
        />
        <mesh
          material={materials.blue}
          geometry={nodes['5-face001'].geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.4, 0.36, 0.4]}
        />
        <mesh material={materials['silver.005']} geometry={nodes['5-Neck'].geometry} scale={[0.26, 0.15, 0.26]} />
        <mesh material={materials['black-grease']} geometry={nodes['5-Neck001'].geometry} scale={[0.26, 0.15, 0.26]} />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh material={materials.blue} geometry={nodes['5-Bodybase'].geometry} />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-gem'].geometry}
          rotation={[1.6, 0, 0]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials['emit-orange.001']}
          geometry={nodes['5-gem001'].geometry}
          rotation={[1.6, 0, 0]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials['silver.002']}
          geometry={nodes['5-shoudlerL'].geometry}
          position={[-1.38, -0.48, 0]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.blue}
          geometry={nodes['5-shoudlerL001'].geometry}
          position={[-1.38, -0.48, 0]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials['silver.002']}
          geometry={nodes['5-shoudlerR'].geometry}
          position={[1.39, -0.48, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.blue}
          geometry={nodes['5-shoudlerR001'].geometry}
          position={[1.39, -0.48, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.blue}
          geometry={nodes['5-Torso'].geometry}
          position={[0, 0.27, 0]}
          scale={[0.69, 0.52, 0.69]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-torso-leg-jointL'].geometry}
          position={[-0.41, -2.31, 0]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-torso-leg-jointR'].geometry}
          position={[0.41, -2.31, 0]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh material={materials['black-grease']} geometry={nodes['5-waist'].geometry} scale={[0.32, 0.2, 0.32]} />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh
          material={materials['black-grease']}
          geometry={nodes['5-ArmsL'].geometry}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.17, 0.17, 0.17]}
        />
        <mesh
          material={materials['black-grease']}
          geometry={nodes['5-armsR'].geometry}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.17, 0.17, 0.17]}
        />
        <mesh material={materials['silver.005']} geometry={nodes['5-finger1L'].geometry} scale={[0.14, 0.1, 0.1]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-finger1R'].geometry} scale={[0.14, 0.1, 0.1]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-finger2L'].geometry} scale={[0.15, 0.11, 0.11]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-finger2R'].geometry} scale={[0.15, 0.11, 0.11]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-finger3L'].geometry} scale={[0.13, 0.09, 0.09]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-finger3R'].geometry} scale={[0.13, 0.09, 0.09]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-handL'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh material={materials.blue} geometry={nodes['5-handL001'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-HandR'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh material={materials.blue} geometry={nodes['5-HandR001'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-thumbL'].geometry}
          rotation={[0, -1.57, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-thumbR'].geometry}
          rotation={[0, -1.57, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh material={materials['silver.001']} geometry={nodes['5-Base'].geometry} scale={[2.32, 0.31, 2.32]} />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-finger-leg1R'].geometry}
          rotation={[0, -1.21, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-finger-leg1R001'].geometry}
          rotation={[0, -1.21, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-finger-leg2L'].geometry}
          rotation={[0, -1.52, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-finger-leg2R'].geometry}
          rotation={[0, -1.52, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-finger-leg3L'].geometry}
          rotation={[Math.PI, -1.2, Math.PI]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials['silver.005']}
          geometry={nodes['5-finger-leg3R'].geometry}
          rotation={[Math.PI, -1.2, Math.PI]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh material={materials.blue} geometry={nodes['5-FootL'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-FootL001'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials.blue} geometry={nodes['5-FootR'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials['silver.005']} geometry={nodes['5-FootR001'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials['black-grease']} geometry={nodes['5-LegsL'].geometry} scale={[0.2, 0.2, 0.2]} />
        <mesh material={materials['black-grease']} geometry={nodes['5-LegsR'].geometry} scale={[0.2, 0.2, 0.2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/compressedv5.glb')
