/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Final_v5.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Ears} geometry={nodes['1-ears'].geometry} />
      <mesh material={materials.EyesInner} geometry={nodes['1-eyes'].geometry} />
      <mesh material={materials.EyesOuter} geometry={nodes['1-eyesOuter'].geometry} />
      <mesh material={materials.FaceBase} geometry={nodes['1-face'].geometry} />
      <mesh material={materials.Joints} geometry={nodes['1-neck'].geometry} />
      <mesh material={materials.BodyBase} geometry={nodes['1-bodybase'].geometry} />
      <mesh material={materials.BodyDetails} geometry={nodes['1-bodyDetails'].geometry} />
      <mesh material={materials.Gem} geometry={nodes['1-gem'].geometry} />
      <mesh material={materials.GemShell} geometry={nodes['1-gemShell'].geometry} />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['1-leg-jointsL'].geometry}
        position={[-0.3, -1.54, 0]}
        rotation={[0, 0, 0.04]}
        scale={[1.16, 1.16, 1.16]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['1-leg-jointsR'].geometry}
        position={[0.31, -1.53, 0]}
        rotation={[0, 0, -0.04]}
        scale={[1.13, 1.13, 1.13]}
      />
      <mesh material={materials.BodyDetails} geometry={nodes['1-screws-body'].geometry} />
      <mesh material={materials.BodyDetails} geometry={nodes['1-screws-body2'].geometry} />
      <mesh material={materials.BodyDetails} geometry={nodes['1-shoulderL'].geometry} />
      <mesh material={materials.BodyDetails} geometry={nodes['1-shoulderR'].geometry} />
      <mesh material={materials.BodyBase} geometry={nodes['1-torso'].geometry} />
      <mesh material={materials['Torso-Details']} geometry={nodes['1-torsoDetails'].geometry} />
      <mesh material={materials.Joints} geometry={nodes['1-waist'].geometry} />
      <mesh material={materials.Joints} geometry={nodes['1-armsL'].geometry} position={[0, 0.12, 0]} />
      <mesh material={materials.Joints} geometry={nodes['1-armsR'].geometry} position={[0, 0.12, 0]} />
      <mesh material={materials.HandDetails} geometry={nodes['1-hand-jointL'].geometry} position={[0, 0.12, 0]} />
      <mesh material={materials.HandDetails} geometry={nodes['1-hand-jointR'].geometry} position={[1.87, -0.28, 0]} />
      <mesh material={materials.HandDetails} geometry={nodes['1-weaponDetailsL'].geometry} position={[0, 0.12, 0]} />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['1-weaponDetailsR'].geometry}
        position={[2.38, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh material={materials.HandDetailsInner} geometry={nodes['1-weaponInnerL'].geometry} position={[0, 0.12, 0]} />
      <mesh
        material={materials.HandDetailsInner}
        geometry={nodes['1-weaponInnerR'].geometry}
        position={[2.38, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh material={materials.Hands} geometry={nodes['1-weaponL'].geometry} position={[0, 0.12, 0]} />
      <mesh
        material={materials.Hands}
        geometry={nodes['1-weaponR'].geometry}
        position={[2.38, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[0, -3.39, 0]}>
        <mesh
          material={materials.BaseMount}
          geometry={nodes['1-BaseMount'].geometry}
          position={[0, 3.39, 0]}
          scale={[1.5, 0.2, 1.5]}
        />
        <mesh material={materials.FootDetails} geometry={nodes['1-foot-jointsL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.FootDetails} geometry={nodes['1-foot-jointsR'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.BodyDetails} geometry={nodes['1-foot-screwsL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.BodyDetails} geometry={nodes['1-foot-screwsR'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.Foot} geometry={nodes['1-footL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.Foot} geometry={nodes['1-footR'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.LowerLeg} geometry={nodes['1-LegL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.LowerLeg} geometry={nodes['1-LegR'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.Joints} geometry={nodes['1-LegsJointL'].geometry} position={[0, 3.39, 0]} />
        <mesh material={materials.Joints} geometry={nodes['1-LegsJointR'].geometry} position={[0, 3.39, 0]} />
      </group>
      <mesh
        material={materials.EyesInner}
        geometry={nodes['2-eyes'].geometry}
        position={[-0.16, 0.31, 0.5]}
        rotation={[-2.04, 0, Math.PI]}
        scale={[0.1, 0.03, 0.1]}
      />
      <mesh
        material={materials.EyeScreen}
        geometry={nodes['2-eyes-screen'].geometry}
        position={[0, 0.05, 0.06]}
        scale={[0.55, 0.55, 0.55]}
      />
      <mesh
        material={materials.FaceBase}
        geometry={nodes['2-face'].geometry}
        position={[0, 0.01, 0]}
        scale={[0.59, 0.59, 0.59]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['2-faceDetails'].geometry}
        position={[0, 0.01, 0]}
        scale={[0.59, 0.59, 0.59]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['2-base-jointsL'].geometry}
        rotation={[0, 0, -0.4]}
        scale={[0.17, 0.09, 0.17]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['2-base-jointsR'].geometry}
        rotation={[0, 0, -0.4]}
        scale={[0.17, 0.09, 0.17]}
      />
      <mesh material={materials.BodyBase} geometry={nodes['2-Bodybase'].geometry} scale={[1.14, 1.25, 1.14]} />
      <mesh
        material={materials.GemShell}
        geometry={nodes['2-gem'].geometry}
        rotation={[1.87, 0, 0]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        material={materials.Gem}
        geometry={nodes['2-gemShell'].geometry}
        rotation={[1.87, 0, 0]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['2-shouldersDetailsL'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['2-shouldersDetailsR'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['2-shouldersL'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['2-shouldersR'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.18, 0.1, 0.18]}
      />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['2-torso'].geometry}
        rotation={[0, 0, Math.PI]}
        scale={[0.65, 0.4, 0.65]}
      />
      <mesh material={materials.Joints} geometry={nodes['2-waist'].geometry} scale={[0.37, 0.22, 0.37]} />
      <mesh
        material={materials.Joints}
        geometry={nodes['2-ArmsjointsL'].geometry}
        position={[-2.02, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.47, 0.09]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['2-ArmsJointsL2'].geometry}
        position={[-1.02, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.47, 0.09]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['2-ArmsJointsR'].geometry}
        position={[-0.69, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['2-ArmsJointsR2'].geometry}
        position={[-1.62, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials.Hands}
        geometry={nodes['2-upper-armsL'].geometry}
        position={[-1.77, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.48, 0.26]}
      />
      <mesh
        material={materials.Hands}
        geometry={nodes['2-upper-armsR'].geometry}
        position={[-1.42, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.48, 0.26]}
      />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['2-WeaponDetailsL'].geometry}
        position={[-3.3, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['2-WeaponDetailsR'].geometry}
        position={[-2.75, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.HandDetailsInner}
        geometry={nodes['2-WeaponInnerL'].geometry}
        position={[-3.2, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.HandDetailsInner}
        geometry={nodes['2-WeaponInnerL2'].geometry}
        position={[-3.2, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.HandDetailsInner}
        geometry={nodes['2-WeaponInnerR'].geometry}
        position={[-2.85, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.HandDetailsInner}
        geometry={nodes['2-WeaponInnerR2'].geometry}
        position={[-2.85, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.Hands}
        geometry={nodes['2-WeaponL'].geometry}
        position={[-3.3, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.Hands}
        geometry={nodes['2-WeaponR'].geometry}
        position={[-2.75, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.26, 0.93, 0.26]}
      />
      <mesh
        material={materials.BaseMount}
        geometry={nodes['2-BaseMount'].geometry}
        position={[0, 0.02, 0]}
        scale={[1.5, 0.2, 1.5]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['2-FootDetailsL'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['2-FootDetailsR'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials.LowerLeg}
        geometry={nodes['2-FootL'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials.LowerLeg}
        geometry={nodes['2-FootR'].geometry}
        position={[-0.34, -3, 0]}
        scale={[0.3, 1.05, 0.3]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['2-LegJointL'].geometry}
        position={[-0.33, -1.98, 0]}
        rotation={[0, 0, -0.05]}
        scale={[0.13, 0.04, 0.13]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['2-LegJointR'].geometry}
        position={[-0.33, -1.98, 0]}
        rotation={[0, 0, -0.05]}
        scale={[0.13, 0.04, 0.13]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['2-LegsL'].geometry}
        position={[-0.31, -1.84, 0]}
        rotation={[0, 0, -0.12]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['2-LegsR'].geometry}
        position={[-0.31, -1.84, 0]}
        rotation={[0, 0, -0.12]}
        scale={[0.09, 0.5, 0.09]}
      />
      <mesh
        material={materials.Ears}
        geometry={nodes['3-Ears'].geometry}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.11, 0.06, 0.11]}
      />
      <mesh
        material={materials.EyesOuter}
        geometry={nodes['3-EyeBase'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh
        material={materials.EyesInner}
        geometry={nodes['3-EyeInner'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh
        material={materials.EyesOuter}
        geometry={nodes['3-EyeOuter'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh
        material={materials.FaceBase}
        geometry={nodes['3-EyeOuterShell'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.1, 0.2]}
      />
      <mesh material={materials.FaceBase} geometry={nodes['3-Face'].geometry} scale={[0.39, 0.39, 0.31]} />
      <mesh material={materials.Joints} geometry={nodes['3-Neck'].geometry} scale={[0.13, 0.1, 0.13]} />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['3-bodybase'].geometry}
        position={[0, 0, 0]}
        scale={[0.65, 0.46, 0.52]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['3-bodyDetails'].geometry}
        position={[0, 0, 0]}
        scale={[0.65, 0.46, 0.52]}
      />
      <mesh
        material={materials.GemShell}
        geometry={nodes['3-gem'].geometry}
        position={[0, 0, 0]}
        rotation={[1.86, 0, 0]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        material={materials.Gem}
        geometry={nodes['3-gemShell'].geometry}
        position={[0, 0, 0]}
        rotation={[1.86, 0, 0]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['3-LegJointL'].geometry}
        position={[0, 0.09, 0]}
        rotation={[0, 0, 0.68]}
        scale={[0.18, 0.09, 0.18]}
      />
      <mesh
        material={materials.FootDetails}
        geometry={nodes['3-LegJointR'].geometry}
        position={[0, 0.09, 0]}
        rotation={[0, 0, 0.68]}
        scale={[0.18, 0.09, 0.18]}
      />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['3-shoulderL'].geometry}
        position={[-0.8, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['3-shoulderL001'].geometry}
        position={[-0.8, -0.28, 0]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['3-shoulderR'].geometry}
        position={[0.8, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['3-shoulderR001'].geometry}
        position={[0.8, -0.28, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        material={materials.BodyBase}
        geometry={nodes['3-torso'].geometry}
        position={[0, 0.09, 0]}
        scale={[0.47, 0.47, 0.47]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['3-waist'].geometry}
        position={[0, 0.05, 0]}
        scale={[0.25, 0.12, 0.25]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['3-elbowL'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.15, 0.15, 0.15]}
      />
      <mesh
        material={materials.BodyDetails}
        geometry={nodes['3-elbowR'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.15, 0.15, 0.15]}
      />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['3-HandDetailsL'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['3-HandDetailsR'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['3-HandL'].geometry}
        position={[0, -0.2, 0]}
        scale={[0.19, 0.05, 0.13]}
      />
      <mesh
        material={materials.HandDetails}
        geometry={nodes['3-handR'].geometry}
        position={[0, -0.2, 0]}
        scale={[0.19, 0.05, 0.13]}
      />
      <mesh
        material={materials.Hands}
        geometry={nodes['3-lowerArmL'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.Hands}
        geometry={nodes['3-lowerArmR'].geometry}
        position={[0, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.45, 0.09]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['3-upper-armsL'].geometry}
        position={[0.03, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.35, 0.09]}
      />
      <mesh
        material={materials.Joints}
        geometry={nodes['3-upper-armsR'].geometry}
        position={[-0.04, -0.2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.35, 0.09]}
      />
      <group position={[0, -0.6, 0]}>
        <mesh
          material={materials.BaseMount}
          geometry={nodes['3-BaseMount'].geometry}
          position={[0, 0.6, 0]}
          scale={[1.5, 0.2, 1.5]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['3-footL'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.16, 0.16, 0.16]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['3-FootR'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.16, 0.16, 0.16]}
        />
        <mesh
          material={materials.LowerLeg}
          geometry={nodes['3-LowerLegL'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          material={materials.LowerLeg}
          geometry={nodes['3-LowerLegR'].geometry}
          position={[0, 0.64, 0]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          material={materials.Joints}
          geometry={nodes['3-thighsL'].geometry}
          position={[0, 0.64, 0]}
          rotation={[0, 0, -2.97]}
          scale={[0.1, 0.5, 0.1]}
        />
        <mesh
          material={materials.Joints}
          geometry={nodes['3-thighsR'].geometry}
          position={[0, 0.64, 0]}
          rotation={[0, 0, -2.97]}
          scale={[0.1, 0.5, 0.1]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials.EyesOuter}
          geometry={nodes['4-eye'].geometry}
          position={[0, 0.63, 0.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.EyesInner}
          geometry={nodes['4-eyeInner'].geometry}
          position={[0, 0.63, 0.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.FaceBase}
          geometry={nodes['4-eyeOuter'].geometry}
          position={[0, 0.63, 0.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.FaceBase}
          geometry={nodes['4-face'].geometry}
          position={[0, 0.41, 0]}
          scale={[0.4, 0.28, 0.4]}
        />
        <mesh
          material={materials.Joints}
          geometry={nodes['4-Neck'].geometry}
          position={[0, 0.06, 0]}
          scale={[0.22, 0.12, 0.17]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials.BodyBase}
          geometry={nodes['4-Body-base'].geometry}
          position={[0, -0.99, 0]}
          scale={[0.99, 0.99, 0.69]}
        />
        <mesh
          material={materials.Gem}
          geometry={nodes['4-gem'].geometry}
          position={[0, -0.39, 0.73]}
          rotation={[1.6, 0, 0]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          material={materials.GemShell}
          geometry={nodes['4-gemShell'].geometry}
          position={[0, -0.39, 0.73]}
          rotation={[1.6, 0, 0]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['4-shoulderL'].geometry}
          position={[-0.9, -0.36, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.26, 0.18, 0.26]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['4-shoulderR'].geometry}
          position={[-0.9, -0.36, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.26, 0.18, 0.26]}
        />
        <mesh
          material={materials.BodyBase}
          geometry={nodes['4-Torso'].geometry}
          position={[0, -1.63, 0]}
          scale={[0.58, 0.58, 0.58]}
        />
        <mesh
          material={materials.Joints}
          geometry={nodes['4-waist'].geometry}
          position={[0, -1.54, 0]}
          scale={[0.36, 0.2, 0.28]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['4-armsDetailsL'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['4-armsDetailsL2'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['4-armsDetailsR'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['4-armsDetailsR2'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.Hands}
          geometry={nodes['4-armsL'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.Hands}
          geometry={nodes['4-armsR'].geometry}
          position={[-1.49, -0.38, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.19, 0.44, 0.19]}
        />
        <mesh
          material={materials.HandDetails}
          geometry={nodes['4-handsDetailsL'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.HandDetails}
          geometry={nodes['4-handsDetailsR'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.HandDetailsInner}
          geometry={nodes['4-handsInnerL'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.HandDetails}
          geometry={nodes['4-handsInnerL2'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.HandDetailsInner}
          geometry={nodes['4-handsInnerR'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.HandDetails}
          geometry={nodes['4-handsInnerR2'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.Hands}
          geometry={nodes['4-handsL'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
        <mesh
          material={materials.Hands}
          geometry={nodes['4-handsR'].geometry}
          position={[-3.37, -0.37, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.2, 0.2, 0.2]}
        />
      </group>
      <group scale={[0.74, 0.74, 0.74]}>
        <mesh
          material={materials.BaseMount}
          geometry={nodes['4-BaseMount'].geometry}
          position={[0, 0.03, 0]}
          scale={[2.01, 0.27, 2.01]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['4-footL'].geometry}
          position={[0.57, -4.52, 0.21]}
          scale={[0.26, 0.24, 0.45]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['4-footR'].geometry}
          position={[0.57, -4.52, 0.21]}
          scale={[0.26, 0.24, 0.45]}
        />
        <mesh
          material={materials.FootDetails}
          geometry={nodes['4-LegsDetailsL'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials.FootDetails}
          geometry={nodes['4-LegsDetailsL2'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials.FootDetails}
          geometry={nodes['4-LegsDetailsR'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials.FootDetails}
          geometry={nodes['4-LegsDetailsR2'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials.LowerLeg}
          geometry={nodes['4-LegsL'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
        <mesh
          material={materials.LowerLeg}
          geometry={nodes['4-LegsR'].geometry}
          position={[-0.43, -2.6, -0.01]}
          rotation={[0, 0, -0.09]}
          scale={[0.19, 0.43, 0.19]}
        />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh
          material={materials.EyesInner}
          geometry={nodes['5-eyes'].geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.12, 0.02, 0.12]}
        />
        <mesh
          material={materials.FaceBase}
          geometry={nodes['5-face'].geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.4, 0.36, 0.4]}
        />
        <mesh
          material={materials.EyeScreen}
          geometry={nodes['5-faceScreen'].geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.4, 0.36, 0.4]}
        />
        <mesh material={materials.Joints} geometry={nodes['5-Neck'].geometry} scale={[0.26, 0.15, 0.26]} />
        <mesh material={materials.BodyDetails} geometry={nodes['5-NeckDetails'].geometry} scale={[0.26, 0.15, 0.26]} />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh material={materials.BodyBase} geometry={nodes['5-Bodybase'].geometry} />
        <mesh
          material={materials.Gem}
          geometry={nodes['5-gem'].geometry}
          rotation={[1.6, 0, 0]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.GemShell}
          geometry={nodes['5-gemShell'].geometry}
          rotation={[1.6, 0, 0]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['5-shoudlerDetailsL'].geometry}
          position={[-1.38, -0.48, 0]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.BodyDetails}
          geometry={nodes['5-shoudlerDetailsR'].geometry}
          position={[1.39, -0.48, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.BodyBase}
          geometry={nodes['5-shoudlerL'].geometry}
          position={[-1.38, -0.48, 0]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.BodyBase}
          geometry={nodes['5-shoudlerR'].geometry}
          position={[1.39, -0.48, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          material={materials.BodyBase}
          geometry={nodes['5-Torso'].geometry}
          position={[0, 0.27, 0]}
          scale={[0.69, 0.52, 0.69]}
        />
        <mesh
          material={materials.FootDetails}
          geometry={nodes['5-torso-leg-jointL'].geometry}
          position={[-0.41, -2.31, 0]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          material={materials.FootDetails}
          geometry={nodes['5-torso-leg-jointR'].geometry}
          position={[0.41, -2.31, 0]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh material={materials.Joints} geometry={nodes['5-waist'].geometry} scale={[0.32, 0.2, 0.32]} />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh
          material={materials.Joints}
          geometry={nodes['5-ArmsL'].geometry}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.17, 0.17, 0.17]}
        />
        <mesh
          material={materials.Joints}
          geometry={nodes['5-armsR'].geometry}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.17, 0.17, 0.17]}
        />
        <mesh material={materials.HandDetails} geometry={nodes['5-finger1L'].geometry} scale={[0.14, 0.1, 0.1]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-finger1R'].geometry} scale={[0.14, 0.1, 0.1]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-finger2L'].geometry} scale={[0.15, 0.11, 0.11]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-finger2R'].geometry} scale={[0.15, 0.11, 0.11]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-finger3L'].geometry} scale={[0.13, 0.09, 0.09]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-finger3R'].geometry} scale={[0.13, 0.09, 0.09]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-handDetailsL'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh material={materials.HandDetails} geometry={nodes['5-HandDetailsR'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh material={materials.Hands} geometry={nodes['5-handL'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh material={materials.Hands} geometry={nodes['5-HandR'].geometry} scale={[0.31, 0.31, 0.31]} />
        <mesh
          material={materials.HandDetails}
          geometry={nodes['5-thumbL'].geometry}
          rotation={[0, -1.57, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials.HandDetails}
          geometry={nodes['5-thumbR'].geometry}
          rotation={[0, -1.57, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
      </group>
      <group scale={[0.65, 0.65, 0.65]}>
        <mesh
          material={materials.BaseMount}
          geometry={nodes['5-BaseMount'].geometry}
          position={[0, 0.03, 0]}
          scale={[2.32, 0.31, 2.32]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['5-finger-leg1L'].geometry}
          rotation={[0, -1.21, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['5-finger-leg1R'].geometry}
          rotation={[0, -1.21, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['5-finger-leg2L'].geometry}
          rotation={[0, -1.52, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['5-finger-leg2R'].geometry}
          rotation={[0, -1.52, 0]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['5-finger-leg3L'].geometry}
          rotation={[Math.PI, -1.2, Math.PI]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh
          material={materials.Foot}
          geometry={nodes['5-finger-leg3R'].geometry}
          rotation={[Math.PI, -1.2, Math.PI]}
          scale={[0.14, 0.1, 0.1]}
        />
        <mesh material={materials.FootDetails} geometry={nodes['5-FootDetailsL'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials.FootDetails} geometry={nodes['5-FootDetailsR'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials.LowerLeg} geometry={nodes['5-FootL'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials.LowerLeg} geometry={nodes['5-FootR'].geometry} scale={[0.25, 0.25, 0.25]} />
        <mesh material={materials.Joints} geometry={nodes['5-LegsL'].geometry} scale={[0.2, 0.2, 0.2]} />
        <mesh material={materials.Joints} geometry={nodes['5-LegsR'].geometry} scale={[0.2, 0.2, 0.2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Final_v5.glb')
